# Generated by Django 3.1.7 on 2021-04-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('about_us', models.TextField(blank=True, null=True)),
                ('github_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'mySetting',
                'verbose_name_plural': 'mySetting',
            },
        ),
    ]
