# Generated by Django 3.1.7 on 2021-04-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='english_cv_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='persian_cv_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
